#!/bin/bash

################################################################################
# Remsana Project Documentation Generator
# This script generates comprehensive project documentation based on the
# product specification and project structure analysis.
# 
# Usage: bash generate-documentation.sh
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Project root
PROJECT_ROOT="$(pwd)"
DOCS_DIR="$PROJECT_ROOT/docs"

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Remsana Project Documentation Generator                    ║"
echo "║     Generating comprehensive project documentation              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Create docs directory structure
echo -e "${YELLOW}[1/8]${NC} Creating documentation directory structure..."
mkdir -p "$DOCS_DIR"/{architecture,api,deployment,development,design-system,user-guides}

# ============================= MAIN DOCUMENTATION =============================

echo -e "${YELLOW}[2/8]${NC} Generating main documentation files..."

# PROJECT_OVERVIEW.md
cat > "$DOCS_DIR/PROJECT_OVERVIEW.md" << 'EOF'
# Remsana: Complete SME Business Builder Platform

## Executive Summary

Remsana is a comprehensive digital platform designed for Nigerian Small and Medium-sized Enterprises (SMEs). The platform combines business registration, skill development through e-learning, and ongoing support to help SME owners succeed in Nigeria's competitive business environment.

**Target Audience:** SME owners and entrepreneurs in Nigeria  
**Primary Goal:** Register businesses, access 100-day training programme, and gain business acumen

---

## Project Structure

```
REMSANA-Business-Builder-1/
├── src/                          # Figma design system (current)
│   ├── app/
│   │   ├── components/
│   │   │   ├── remsana/          # Brand components
│   │   │   └── ui/               # Base UI components
│   │   └── App.tsx
│   └── styles/                   # Design tokens
├── setup-remsana.sh              # Full project generator
├── generate-documentation.sh     # Documentation generator
├── docs/                         # Project documentation
└── [Generated by setup-remsana.sh]
    ├── remsana-web/              # React web application
    └── remsana-mobile/           # React Native mobile app
```

---

## Key Features

### 1. Business Registration Portal
- Multi-step business registration process
- Business type classification (sole proprietorship, partnership, LLC, public company)
- Document upload and verification
- Registration status tracking
- Compliance guidance and requirements

### 2. Learning Management System
- 100-day structured e-learning course
- Video lessons with captions
- Interactive quizzes after each lesson
- Downloadable resources (workbooks, templates, Excel sheets)
- Progress tracking with completion certificates

### 3. Dashboard & Analytics
- Personalized SME owner dashboard
- Learning progress visualization
- Business registration status
- Certificates earned
- Recommended next steps and resources

### 4. Mobile Application
- Full feature parity with web platform
- Offline access to downloaded lessons
- Push notifications for milestones
- Native iOS and Android apps
- Optimized for slow network speeds

---

## Technology Stack

**Frontend (Web):**
- React 18.2.0
- Vite 4.5.0
- Tailwind CSS 3.3.5
- React Router 6.16.0
- Axios 1.5.0
- React Query 3.39.3

**Mobile:**
- React Native 0.73.0
- Expo ~50.0.0
- Expo Router ~2.4.0
- NativeWind 2.0.0
- Secure Store for token storage

**Backend Integration:**
- RESTful API architecture (Laravel backend)
- JWT token-based authentication
- Request/response interceptors
- Error handling and 401 recovery

**DevOps:**
- Docker containerization
- Docker Compose for local development
- GitHub Actions CI/CD pipelines
- Environment-based configuration

---

## Quick Start

### For Design System (Current Folder)
```bash
npm install
npm run dev
```

### For Full Project Setup
```bash
bash setup-remsana.sh
cd remsana
bash install.sh
```

### For Documentation
```bash
bash generate-documentation.sh
```

---

## Documentation Index

- [Architecture Documentation](architecture/README.md)
- [API Documentation](api/README.md)
- [Deployment Guide](deployment/README.md)
- [Development Guide](development/README.md)
- [Design System Guide](design-system/README.md)
- [User Guides](user-guides/README.md)

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

# ARCHITECTURE.md
cat > "$DOCS_DIR/architecture/ARCHITECTURE.md" << 'EOF'
# Remsana Architecture Documentation

## System Architecture Overview

Remsana follows a modern, scalable architecture with clear separation between frontend, backend, and infrastructure layers.

```
┌─────────────────────────────────────────────────────────────┐
│                     Client Layer                             │
├─────────────────────┬───────────────────────────────────────┤
│   Web Application   │      Mobile Application               │
│   (React + Vite)    │   (React Native + Expo)              │
└──────────┬──────────┴──────────────┬──────────────────────┘
           │                         │
           │  HTTPS / REST API       │
           │                         │
┌──────────▼─────────────────────────▼──────────────────────┐
│              API Gateway / Load Balancer                    │
└──────────┬──────────────────────────────────────────────────┘
           │
┌──────────▼──────────────────────────────────────────────────┐
│                    Backend API Layer                        │
│                  (Laravel Framework)                        │
│  ┌──────────┐  ┌──────────┐  ┌──────────┐  ┌──────────┐     │
│  │  Auth    │  │ Business │  │ Learning │  │  Media  │     │
│  │ Service  │  │ Service  │  │ Service  │  │ Service │     │
│  └──────────┘  └──────────┘  └──────────┘  └──────────┘     │
└──────────┬──────────────────────────────────────────────────┘
           │
┌──────────▼──────────────────────────────────────────────────┐
│                    Data Layer                               │
│  ┌──────────────┐  ┌──────────────┐  ┌──────────────┐     │
│  │   Primary    │  │   Read       │  │   Cache      │     │
│  │   Database    │  │   Replica    │  │   (Redis)    │     │
│  └──────────────┘  └──────────────┘  └──────────────┘     │
└─────────────────────────────────────────────────────────────┘
```

---

## Frontend Architecture

### Web Application Structure

```
remsana-web/
├── src/
│   ├── components/
│   │   ├── Auth/              # Authentication components
│   │   ├── Dashboard/         # Dashboard widgets
│   │   ├── Learning/          # Learning components
│   │   ├── BusinessRegistration/  # Registration forms
│   │   └── Common/            # Shared components
│   ├── context/               # React Context providers
│   │   ├── AuthContext.jsx
│   │   └── LearningContext.jsx
│   ├── services/              # API service layer
│   │   ├── api.js            # Axios instance
│   │   ├── authService.js
│   │   ├── courseService.js
│   │   ├── learningService.js
│   │   └── registrationService.js
│   ├── utils/                # Utility functions
│   │   ├── storage.js
│   │   ├── validators.js
│   │   └── constants.js
│   └── pages/                # Page components
│       ├── HomePage.jsx
│       ├── LoginPage.jsx
│       ├── DashboardPage.jsx
│       ├── RegistrationPage.jsx
│       └── LessonPage.jsx
```

### Mobile Application Structure

```
remsana-mobile/
├── app/                      # Expo Router file-based routing
│   ├── (auth)/              # Auth stack
│   │   ├── login.tsx
│   │   └── signup.tsx
│   └── (tabs)/              # Main app tabs
│       ├── dashboard.tsx
│       ├── learning.tsx
│       └── profile.tsx
├── src/
│   ├── components/          # Reusable components
│   ├── context/             # State management
│   ├── services/            # API clients
│   └── utils/               # Helpers
```

---

## State Management

### Context API Pattern

**Authentication Context:**
- User state
- Token management
- Authentication status
- Login/logout actions

**Learning Context:**
- Course data
- Progress tracking
- Quiz answers
- Downloaded resources

### State Flow

```
User Action
    ↓
Component Event Handler
    ↓
Context Dispatch (useReducer)
    ↓
Service Layer (API Call)
    ↓
Backend API
    ↓
Response → Context Update
    ↓
Component Re-render
```

---

## API Architecture

### RESTful API Design

**Base URL:** `https://api.remsana.com/api`

**Authentication:**
- JWT token-based
- Token in Authorization header: `Bearer <token>`
- Refresh token mechanism
- Automatic token refresh on 401

**Endpoints:**

```
POST   /auth/login
POST   /auth/register
POST   /auth/logout
POST   /auth/refresh

GET    /businesses/registration-status
POST   /businesses/register

GET    /courses
GET    /courses/:id
POST   /enrollments

GET    /lessons/:id
POST   /lessons/:id/complete
POST   /lessons/:id/quiz

GET    /resources/:id/download
```

### Request/Response Format

**Request:**
```json
{
  "email": "user@example.com",
  "password": "password123"
}
```

**Response:**
```json
{
  "success": true,
  "data": {
    "user": { ... },
    "token": "jwt_token_here",
    "refreshToken": "refresh_token_here"
  }
}
```

---

## Data Flow

### Authentication Flow

```
1. User submits login form
2. Frontend calls authService.login()
3. Axios interceptor adds token to request
4. Backend validates credentials
5. Backend returns JWT token
6. Frontend stores token (localStorage/SecureStore)
7. Context updates with user data
8. User redirected to dashboard
```

### Learning Flow

```
1. User navigates to learning center
2. Frontend fetches courses via courseService
3. User selects course
4. Frontend fetches lessons
5. User watches video lesson
6. User completes quiz
7. Frontend submits quiz answers
8. Backend validates and scores
9. Progress updated in context
10. Certificate issued on completion
```

---

## Security Architecture

### Authentication & Authorization

**JWT Token Management:**
- Access token: 15-minute expiration
- Refresh token: 7-day expiration
- Secure storage (localStorage web, SecureStore mobile)
- Automatic refresh on 401

**Protected Routes:**
- AuthGuard component wraps protected pages
- Redirects to login if unauthenticated
- Token validation on app startup

### Data Protection

**Encryption:**
- HTTPS/TLS 1.2+ for all traffic
- Encrypted password storage (bcrypt)
- Encrypted backups

**Access Control:**
- Role-based access control (RBAC)
- Rate limiting on sensitive endpoints
- Account lockout after failed attempts

---

## Scalability Architecture

### Horizontal Scaling

**Frontend:**
- Stateless applications
- CDN for static assets
- Load balancing across instances

**Backend:**
- Stateless API design
- Database read replicas
- Redis caching layer
- Container orchestration ready

### Performance Optimization

**Frontend:**
- Code splitting
- Lazy loading
- Image optimization
- Service worker caching

**Backend:**
- Query optimization
- Database indexing
- Response caching
- Connection pooling

---

## Deployment Architecture

### Development Environment

```
Docker Compose
├── remsana-web (port 3000)
├── remsana-mobile (port 8081)
└── [Backend API] (port 8000)
```

### Production Environment

```
Cloud Provider (AWS/GCP)
├── ECS/Cloud Run (Web App)
├── ECS/Cloud Run (Mobile Dev Server)
├── API Gateway
├── Load Balancer
├── Application Servers
├── Database (Primary + Replicas)
└── Redis Cache
```

---

## Monitoring & Logging

### Application Monitoring

- Error tracking (Sentry)
- Performance monitoring (New Relic)
- Uptime monitoring
- User analytics (Google Analytics)

### Infrastructure Monitoring

- Container health checks
- CPU and memory usage
- Database performance
- Network latency

### Logging

- Centralized log aggregation (ELK Stack)
- Error logs with stack traces
- API request/response logging
- User action audit logs

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

# API_DOCUMENTATION.md
cat > "$DOCS_DIR/api/API_DOCUMENTATION.md" << 'EOF'
# Remsana API Documentation

## Base URL

**Development:** `http://localhost:8000/api`  
**Production:** `https://api.remsana.com/api`

---

## Authentication

All protected endpoints require a JWT token in the Authorization header:

```
Authorization: Bearer <access_token>
```

---

## Authentication Endpoints

### POST /auth/login

Login with email and password.

**Request:**
```json
{
  "email": "user@example.com",
  "password": "password123"
}
```

**Response (200):**
```json
{
  "success": true,
  "data": {
    "user": {
      "id": 1,
      "email": "user@example.com",
      "name": "John Doe"
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    "refreshToken": "refresh_token_here"
  }
}
```

**Error Response (401):**
```json
{
  "success": false,
  "message": "Invalid credentials"
}
```

---

### POST /auth/register

Register a new user account.

**Request:**
```json
{
  "email": "user@example.com",
  "password": "password123",
  "name": "John Doe",
  "phone": "+2348012345678"
}
```

**Response (201):**
```json
{
  "success": true,
  "data": {
    "user": { ... },
    "token": "...",
    "refreshToken": "..."
  }
}
```

---

### POST /auth/refresh

Refresh access token using refresh token.

**Request:**
```json
{
  "refreshToken": "refresh_token_here"
}
```

**Response (200):**
```json
{
  "success": true,
  "data": {
    "token": "new_access_token",
    "refreshToken": "new_refresh_token"
  }
}
```

---

### POST /auth/logout

Logout and invalidate tokens.

**Headers:**
```
Authorization: Bearer <access_token>
```

**Response (200):**
```json
{
  "success": true,
  "message": "Logged out successfully"
}
```

---

## Business Registration Endpoints

### GET /businesses/registration-status

Get current registration status for authenticated user.

**Headers:**
```
Authorization: Bearer <access_token>
```

**Response (200):**
```json
{
  "success": true,
  "data": {
    "status": "in_progress",
    "progress": 60,
    "currentStep": 3,
    "totalSteps": 5,
    "submittedDocuments": ["business_plan.pdf"],
    "pendingDocuments": ["tax_id.pdf"]
  }
}
```

---

### POST /businesses/register

Submit business registration.

**Headers:**
```
Authorization: Bearer <access_token>
Content-Type: multipart/form-data
```

**Request (Form Data):**
```
businessType: "sole_proprietorship"
businessName: "My Business Ltd"
businessAddress: "123 Main St, Lagos"
industry: "Technology"
documents: [file1, file2]
```

**Response (201):**
```json
{
  "success": true,
  "data": {
    "registrationId": "REG-12345",
    "status": "pending_review",
    "estimatedReviewTime": "24-48 hours"
  }
}
```

---

## Course Endpoints

### GET /courses

Get all available courses.

**Headers:**
```
Authorization: Bearer <access_token>
```

**Response (200):**
```json
{
  "success": true,
  "data": [
    {
      "id": 1,
      "title": "100-Day SME Business Builder",
      "description": "Complete business training program",
      "duration": 100,
      "lessons": 20,
      "thumbnail": "https://cdn.remsana.com/courses/1.jpg"
    }
  ]
}
```

---

### GET /courses/:id

Get course details.

**Response (200):**
```json
{
  "success": true,
  "data": {
    "id": 1,
    "title": "100-Day SME Business Builder",
    "description": "...",
    "modules": [
      {
        "id": 1,
        "title": "Business Fundamentals",
        "lessons": [...]
      }
    ]
  }
}
```

---

### POST /enrollments

Enroll in a course.

**Request:**
```json
{
  "courseId": 1
}
```

**Response (201):**
```json
{
  "success": true,
  "data": {
    "enrollmentId": "ENR-123",
    "courseId": 1,
    "startDate": "2026-01-27",
    "progress": 0
  }
}
```

---

## Learning Endpoints

### GET /lessons/:id

Get lesson details.

**Response (200):**
```json
{
  "success": true,
  "data": {
    "id": 1,
    "title": "Introduction to Business Planning",
    "description": "...",
    "videoUrl": "https://cdn.remsana.com/videos/1.mp4",
    "duration": 600,
    "transcript": "...",
    "resources": [
      {
        "id": 1,
        "name": "Business Plan Template",
        "type": "pdf",
        "url": "https://cdn.remsana.com/resources/1.pdf"
      }
    ],
    "quiz": {
      "id": 1,
      "questions": [...]
    }
  }
}
```

---

### POST /lessons/:id/complete

Mark lesson as completed.

**Response (200):**
```json
{
  "success": true,
  "data": {
    "lessonId": 1,
    "completedAt": "2026-01-27T10:30:00Z",
    "progress": 5
  }
}
```

---

### POST /lessons/:id/quiz

Submit quiz answers.

**Request:**
```json
{
  "answers": {
    "1": "a",
    "2": "b",
    "3": "c"
  }
}
```

**Response (200):**
```json
{
  "success": true,
  "data": {
    "score": 85,
    "passed": true,
    "feedback": "Great job!",
    "correctAnswers": {
      "1": "a",
      "2": "b",
      "3": "c"
    }
  }
}
```

---

## Resource Endpoints

### GET /resources/:id/download

Download a resource file.

**Response:**
- Content-Type: application/pdf (or appropriate type)
- Content-Disposition: attachment; filename="resource.pdf"
- Binary file data

---

## Error Responses

All endpoints may return error responses:

**400 Bad Request:**
```json
{
  "success": false,
  "message": "Validation failed",
  "errors": {
    "email": ["The email field is required."]
  }
}
```

**401 Unauthorized:**
```json
{
  "success": false,
  "message": "Unauthenticated"
}
```

**403 Forbidden:**
```json
{
  "success": false,
  "message": "Unauthorized"
}
```

**404 Not Found:**
```json
{
  "success": false,
  "message": "Resource not found"
}
```

**500 Internal Server Error:**
```json
{
  "success": false,
  "message": "Internal server error"
}
```

---

## Rate Limiting

API endpoints are rate-limited:
- Authentication endpoints: 5 requests per minute
- Other endpoints: 100 requests per minute

Rate limit headers:
```
X-RateLimit-Limit: 100
X-RateLimit-Remaining: 99
X-RateLimit-Reset: 1643299200
```

---

## Pagination

List endpoints support pagination:

**Query Parameters:**
- `page` (default: 1)
- `per_page` (default: 15, max: 100)

**Response:**
```json
{
  "success": true,
  "data": [...],
  "meta": {
    "current_page": 1,
    "per_page": 15,
    "total": 100,
    "last_page": 7
  }
}
```

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

# Continue with remaining documentation files...
echo -e "${YELLOW}[3/8]${NC} Generating deployment documentation..."

cat > "$DOCS_DIR/deployment/DEPLOYMENT.md" << 'EOF'
# Remsana Deployment Guide

## Overview

This guide covers deployment strategies for the Remsana platform, including local development, staging, and production environments.

---

## Local Development

### Using Docker Compose

```bash
# Start all services
docker-compose up --build

# View logs
docker-compose logs -f

# Stop services
docker-compose down
```

**Services:**
- Web app: http://localhost:3000
- Mobile dev server: http://localhost:8081
- Backend API: http://localhost:8000

### Manual Setup

**Web Application:**
```bash
cd remsana-web
npm install
cp .env.example .env.development
npm run dev
```

**Mobile Application:**
```bash
cd remsana-mobile
npm install
cp .env.example .env
npm start
```

---

## Staging Environment

### Prerequisites

- Docker and Docker Compose installed
- Domain name configured
- SSL certificates
- Container registry access

### Deployment Steps

1. **Build Docker Images:**
```bash
docker build -t remsana-web:staging -f remsana-web/Dockerfile .
docker build -t remsana-mobile:staging -f remsana-mobile/Dockerfile .
```

2. **Push to Registry:**
```bash
docker tag remsana-web:staging registry.example.com/remsana-web:staging
docker push registry.example.com/remsana-web:staging
```

3. **Deploy:**
```bash
# Update docker-compose.staging.yml with image tags
docker-compose -f docker-compose.staging.yml up -d
```

---

## Production Deployment

### AWS ECS Deployment

**1. Create ECR Repository:**
```bash
aws ecr create-repository --repository-name remsana-web
aws ecr create-repository --repository-name remsana-mobile
```

**2. Build and Push:**
```bash
# Web app
docker build -t remsana-web:latest -f remsana-web/Dockerfile .
docker tag remsana-web:latest <account>.dkr.ecr.<region>.amazonaws.com/remsana-web:latest
docker push <account>.dkr.ecr.<region>.amazonaws.com/remsana-web:latest

# Mobile app
docker build -t remsana-mobile:latest -f remsana-mobile/Dockerfile .
docker tag remsana-mobile:latest <account>.dkr.ecr.<region>.amazonaws.com/remsana-mobile:latest
docker push <account>.dkr.ecr.<region>.amazonaws.com/remsana-mobile:latest
```

**3. Create ECS Task Definition:**
```json
{
  "family": "remsana-web",
  "containerDefinitions": [{
    "name": "remsana-web",
    "image": "<account>.dkr.ecr.<region>.amazonaws.com/remsana-web:latest",
    "portMappings": [{
      "containerPort": 3000,
      "protocol": "tcp"
    }],
    "environment": [
      {"name": "VITE_API_URL", "value": "https://api.remsana.com/api"}
    ]
  }]
}
```

**4. Create ECS Service:**
```bash
aws ecs create-service \
  --cluster remsana-cluster \
  --service-name remsana-web \
  --task-definition remsana-web \
  --desired-count 2 \
  --launch-type FARGATE
```

### Google Cloud Run Deployment

**1. Build and Push:**
```bash
gcloud builds submit --tag gcr.io/<project-id>/remsana-web
```

**2. Deploy:**
```bash
gcloud run deploy remsana-web \
  --image gcr.io/<project-id>/remsana-web \
  --platform managed \
  --region us-central1 \
  --allow-unauthenticated
```

---

## Environment Variables

### Web Application

```bash
VITE_API_URL=https://api.remsana.com/api
VITE_APP_NAME=Remsana
VITE_APP_VERSION=1.0.0
VITE_APP_ENV=production
```

### Mobile Application

```bash
EXPO_PUBLIC_API_URL=https://api.remsana.com/api
EXPO_PUBLIC_APP_NAME=Remsana
```

---

## CI/CD Pipeline

### GitHub Actions

**Web CI/CD (.github/workflows/web-ci.yml):**
- Lint code
- Run tests
- Build Docker image
- Push to registry
- Deploy to staging/production

**Mobile CI/CD (.github/workflows/mobile-ci.yml):**
- Type check
- Build via EAS
- Upload to app stores (beta)

---

## Health Checks

### Web Application

```bash
curl http://localhost:3000/health
```

Expected response:
```json
{
  "status": "healthy",
  "timestamp": "2026-01-27T10:00:00Z"
}
```

### Mobile Application

Health check via Expo dev server:
```bash
curl http://localhost:8081/status
```

---

## Monitoring

### Application Monitoring

- **Error Tracking:** Sentry
- **Performance:** New Relic
- **Uptime:** Statuspage
- **Analytics:** Google Analytics

### Infrastructure Monitoring

- Container health checks
- CPU and memory usage
- Database performance
- Network latency

---

## Rollback Procedure

### ECS Rollback

```bash
# List task definitions
aws ecs list-task-definitions --family-prefix remsana-web

# Update service to previous version
aws ecs update-service \
  --cluster remsana-cluster \
  --service remsana-web \
  --task-definition remsana-web:<previous-version>
```

### Cloud Run Rollback

```bash
# List revisions
gcloud run revisions list --service remsana-web

# Rollback to previous revision
gcloud run services update-traffic remsana-web \
  --to-revisions <previous-revision>=100
```

---

## Backup & Recovery

### Database Backups

- Automated daily backups
- Retention: 30 days
- Point-in-time recovery available

### Application Backups

- Docker images tagged with versions
- Configuration files version controlled
- Environment variables stored securely

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

echo -e "${YELLOW}[4/8]${NC} Generating development guide..."

cat > "$DOCS_DIR/development/DEVELOPMENT_GUIDE.md" << 'EOF'
# Remsana Development Guide

## Getting Started

### Prerequisites

- Node.js 18+ and npm
- Docker and Docker Compose (optional)
- Git
- Code editor (VS Code recommended)

### Initial Setup

1. **Clone Repository:**
```bash
git clone <repository-url>
cd REMSANA-Business-Builder-1
```

2. **Install Dependencies:**
```bash
npm install
```

3. **Start Development Server:**
```bash
npm run dev
```

---

## Project Structure

### Design System (Current Folder)

```
src/
├── app/
│   ├── components/
│   │   ├── remsana/      # Brand components
│   │   └── ui/           # Base UI components
│   └── App.tsx
├── styles/
│   ├── theme.css         # Design tokens
│   └── tailwind.css
└── assets/               # Figma assets
```

### Full Project (Generated)

```
remsana/
├── remsana-web/          # React web app
├── remsana-mobile/       # React Native app
└── docker-compose.yml
```

---

## Development Workflow

### 1. Design System Development

**Adding a New Component:**

1. Create component file in `src/app/components/remsana/`
2. Follow existing component patterns
3. Use design tokens from `theme.css`
4. Export from `index.ts`
5. Add to Storybook (if available)

**Example:**
```typescript
// src/app/components/remsana/NewComponent.tsx
import React from 'react';

export function NewComponent({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-white rounded-[8px] p-4">
      {children}
    </div>
  );
}
```

### 2. Web Application Development

**Adding a New Page:**

1. Create page component in `remsana-web/src/pages/`
2. Add route in `App.jsx`
3. Create service if needed in `services/`
4. Update navigation if required

**Example:**
```jsx
// remsana-web/src/pages/NewPage.jsx
export default function NewPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <h1>New Page</h1>
    </div>
  );
}
```

### 3. Mobile Application Development

**Adding a New Screen:**

1. Create screen file in `remsana-mobile/app/`
2. Expo Router handles routing automatically
3. Use NativeWind for styling

**Example:**
```tsx
// remsana-mobile/app/newscreen.tsx
import { View, Text } from 'react-native';

export default function NewScreen() {
  return (
    <View className="flex-1 bg-gray-50 p-4">
      <Text className="text-2xl font-bold">New Screen</Text>
    </View>
  );
}
```

---

## Code Style Guidelines

### TypeScript/JavaScript

- Use TypeScript for new code
- Follow ESLint configuration
- Use functional components with hooks
- Prefer named exports

### Styling

- Use Tailwind CSS utility classes
- Reference design tokens from `theme.css`
- Mobile-first responsive design
- Consistent spacing (multiples of 8px)

### Component Structure

```typescript
// 1. Imports
import React from 'react';

// 2. Types/Interfaces
interface ComponentProps {
  // ...
}

// 3. Component
export function Component({ ... }: ComponentProps) {
  // 4. Hooks
  const [state, setState] = useState();
  
  // 5. Handlers
  const handleClick = () => { ... };
  
  // 6. Render
  return (
    // JSX
  );
}
```

---

## Testing

### Running Tests

```bash
# Web app tests
cd remsana-web
npm test

# Mobile app tests
cd remsana-mobile
npm test
```

### Test Structure

```
__tests__/
├── components/
├── services/
└── utils/
```

---

## API Integration

### Making API Calls

**Web:**
```javascript
import api from './services/api';

const response = await api.get('/courses');
```

**Mobile:**
```typescript
import api from '../services/api';

const response = await api.get('/courses');
```

### Error Handling

```javascript
try {
  const response = await api.post('/auth/login', data);
  // Handle success
} catch (error) {
  if (error.response?.status === 401) {
    // Handle unauthorized
  }
  // Handle other errors
}
```

---

## State Management

### Context API

**Creating a Context:**
```javascript
// context/NewContext.jsx
import { createContext, useContext, useReducer } from 'react';

export const NewContext = createContext(null);

export function NewProvider({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <NewContext.Provider value={{ state, dispatch }}>
      {children}
    </NewContext.Provider>
  );
}

export const useNew = () => {
  const context = useContext(NewContext);
  if (!context) throw new Error('useNew must be used within NewProvider');
  return context;
};
```

---

## Git Workflow

### Branch Strategy

- `main` - Production-ready code
- `develop` - Integration branch
- `feature/*` - Feature branches
- `bugfix/*` - Bug fixes
- `hotfix/*` - Critical fixes

### Commit Messages

```
feat: Add business registration form
fix: Resolve authentication token refresh issue
docs: Update API documentation
style: Format code with Prettier
refactor: Extract common validation logic
test: Add unit tests for auth service
```

---

## Debugging

### Web Application

**Browser DevTools:**
- React DevTools extension
- Network tab for API calls
- Console for errors

**VS Code Debugging:**
```json
{
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:5173"
}
```

### Mobile Application

**React Native Debugger:**
- Shake device or Cmd+D (iOS) / Cmd+M (Android)
- Enable remote debugging
- Use Chrome DevTools

**Expo DevTools:**
- Access at http://localhost:19002
- View logs and errors
- Test on physical device via Expo Go

---

## Performance Optimization

### Code Splitting

```javascript
// Lazy load components
const Dashboard = lazy(() => import('./pages/DashboardPage'));

<Suspense fallback={<Loading />}>
  <Dashboard />
</Suspense>
```

### Image Optimization

- Use WebP format
- Lazy load images
- Provide fallbacks
- Use CDN for assets

### Bundle Analysis

```bash
npm run build
npm run analyze  # If configured
```

---

## Troubleshooting

### Common Issues

**Port Already in Use:**
```bash
# Find process
lsof -i :5173

# Kill process
kill -9 <PID>
```

**Module Not Found:**
```bash
# Clear cache and reinstall
rm -rf node_modules package-lock.json
npm install
```

**Docker Issues:**
```bash
# Rebuild containers
docker-compose down
docker-compose up --build
```

---

## Resources

- [React Documentation](https://react.dev/)
- [React Native Documentation](https://reactnative.dev/)
- [Expo Documentation](https://docs.expo.dev/)
- [Tailwind CSS Documentation](https://tailwindcss.com/)
- [Vite Documentation](https://vitejs.dev/)

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

echo -e "${YELLOW}[5/8]${NC} Generating design system documentation..."

cat > "$DOCS_DIR/design-system/DESIGN_SYSTEM.md" << 'EOF'
# Remsana Design System

## Overview

The Remsana design system provides a comprehensive set of components, tokens, and guidelines to ensure consistency across web and mobile platforms.

---

## Design Tokens

### Colors

**Primary Colors:**
- `#1C1C8B` - Primary blue (buttons, links, CTAs)
- `#051d59` - Primary hover state
- `#111d3b` - Primary active state

**Accent Colors:**
- `#eda51f` - Gold accent (highlights, warnings)
- `#a16b08` - Gold hover state
- `#7a530a` - Gold active state

**Neutral Colors:**
- `#1F2121` - Primary text, headings
- `#6B7C7C` - Secondary text, labels
- `#f3f0fa` - Background, light surfaces
- `#FFFFFF` - White, cards

**Semantic Colors:**
- `#C01F2F` - Error, destructive actions
- `#218D8D` - Success states
- `#A84B2F` - Warning states
- `#626C71` - Info states

### Typography

**Font Family:**
- Primary: `Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`

**Font Sizes:**
- H1: `32px` - Page titles
- H2: `24px` - Section headers
- H3: `18px` - Card titles
- Body Large: `16px` - Important text
- Body: `14px` - Standard text
- Body Small: `12px` - Labels, captions

**Font Weights:**
- Normal: `400`
- Medium: `500`
- Semibold: `600`

**Line Heights:**
- H1/H2: `1.2`
- H3: `1.3`
- Body: `1.5`
- Body Small: `1.4`

### Spacing

Multiples of 8px:
- `4px` - Tight spacing
- `8px` - Standard spacing
- `12px` - Medium spacing
- `16px` - Section spacing
- `24px` - Large spacing
- `32px` - Extra large spacing
- `48px` - Maximum spacing

### Border Radius

- Small: `4px`
- Medium: `8px` (default)
- Large: `12px`
- Full: `99px` (pills, badges)

---

## Components

### Button

**Variants:**
- `primary` - Blue background, white text
- `secondary` - White background, blue border
- `tertiary` - Transparent, blue text
- `danger` - Red background, white text

**Sizes:**
- `sm` - 32px height
- `md` - 40px height (default)
- `lg` - 48px height

**Usage:**
```tsx
<Button variant="primary" size="lg">
  Click Me
</Button>
```

### Card

**Variants:**
- `basic` - Standard card
- `hoverable` - Adds hover shadow
- `clickable` - Adds click feedback

**Padding:**
- `sm` - 16px
- `md` - 24px (default)
- `lg` - 32px

**Usage:**
```tsx
<Card variant="hoverable" padding="md">
  <CardHeader>
    <CardTitle>Title</CardTitle>
  </CardHeader>
  <CardContent>
    Content
  </CardContent>
</Card>
```

### Input

**Types:**
- `text` - Standard text input
- `email` - Email input
- `password` - Password input
- `number` - Number input

**States:**
- Default
- Focus
- Error
- Disabled

**Usage:**
```tsx
<Input
  type="email"
  placeholder="Enter email"
  error="Invalid email"
/>
```

### Radio Group

**Usage:**
```tsx
<RadioGroup
  options={[
    { label: 'Option 1', value: '1' },
    { label: 'Option 2', value: '2' }
  ]}
  value={selected}
  onChange={setSelected}
/>
```

### Checkbox

**Usage:**
```tsx
<Checkbox
  checked={isChecked}
  onChange={setIsChecked}
  label="Accept terms"
/>
```

### Progress

**Types:**
- `LinearProgress` - Horizontal progress bar
- `CircularProgress` - Circular progress indicator

**Usage:**
```tsx
<LinearProgress value={60} max={100} />
```

### Badge

**Variants:**
- `default` - Gray
- `primary` - Blue
- `success` - Green
- `warning` - Orange
- `error` - Red

**Usage:**
```tsx
<Badge variant="primary">New</Badge>
```

### Alert

**Variants:**
- `info` - Blue
- `success` - Green
- `warning` - Orange
- `error` - Red

**Usage:**
```tsx
<Alert variant="success">
  Operation completed successfully
</Alert>
```

### Modal

**Sizes:**
- `sm` - 400px width
- `md` - 600px width (default)
- `lg` - 800px width
- `xl` - 1200px width

**Usage:**
```tsx
<Modal
  isOpen={isOpen}
  onClose={() => setIsOpen(false)}
  title="Modal Title"
  size="md"
>
  Modal content
</Modal>
```

### Toast

**Usage:**
```tsx
<Toast
  message="Success message"
  type="success"
  duration={3000}
/>
```

---

## Layout Patterns

### Container

```tsx
<div className="max-w-7xl mx-auto px-4">
  Content
</div>
```

### Grid

```tsx
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
  {items.map(item => <Card key={item.id}>{item.content}</Card>)}
</div>
```

### Flex

```tsx
<div className="flex items-center justify-between gap-4">
  <div>Left</div>
  <div>Right</div>
</div>
```

---

## Responsive Design

### Breakpoints

- Mobile: `< 640px`
- Tablet: `640px - 1024px`
- Desktop: `> 1024px`

### Mobile-First Approach

```tsx
<div className="
  p-4          // Mobile: 16px
  md:p-6       // Tablet: 24px
  lg:p-8       // Desktop: 32px
">
```

---

## Accessibility

### Focus States

All interactive elements have visible focus states:
- 3px solid blue outline
- 2px offset

### ARIA Labels

```tsx
<button aria-label="Close modal">
  <X />
</button>
```

### Keyboard Navigation

- Tab to navigate
- Enter/Space to activate
- Escape to close modals

---

## Usage Guidelines

### Do's

✅ Use design tokens for colors and spacing  
✅ Follow component variants  
✅ Maintain consistent spacing  
✅ Use semantic HTML  
✅ Include ARIA labels  
✅ Test on multiple devices  

### Don'ts

❌ Don't use hard-coded colors  
❌ Don't create custom components without checking existing ones  
❌ Don't skip accessibility features  
❌ Don't use arbitrary spacing values  
❌ Don't ignore responsive design  

---

## Figma Integration

Design tokens and components are synced from Figma:
- Colors match Figma design tokens
- Components follow Figma specifications
- Spacing uses Figma spacing system
- Typography matches Figma text styles

**Figma File:** https://www.figma.com/design/4cYe5d5idQXfUhJ3tF0YXv/REMSANA-Business-Builder

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

echo -e "${YELLOW}[6/8]${NC} Generating user guides..."

cat > "$DOCS_DIR/user-guides/USER_GUIDE.md" << 'EOF'
# Remsana User Guide

## Getting Started

### Creating an Account

1. Visit www.remsana.com
2. Click "Sign Up"
3. Enter your email and create a password
4. Verify your email address
5. Complete your profile

### First Steps

1. **Complete Profile**
   - Add your name and phone number
   - Select your business type
   - Enter basic business information

2. **Register Your Business**
   - Go to "Business Registration"
   - Fill out the multi-step form
   - Upload required documents
   - Submit for review

3. **Start Learning**
   - Access "Learning Centre"
   - Enroll in the 100-day programme
   - Watch your first lesson
   - Complete quizzes

---

## Business Registration

### Step-by-Step Process

1. **Select Business Type**
   - Sole Proprietorship
   - Partnership
   - Limited Liability Company
   - Public Limited Company

2. **Enter Business Information**
   - Business name
   - Business address
   - Industry/sector
   - Number of employees

3. **Upload Documents**
   - Business plan
   - Tax identification
   - Registration documents
   - Other required files

4. **Review and Submit**
   - Review all information
   - Verify documents
   - Submit for approval

### Registration Status

- **Pending** - Under review (24-48 hours)
- **Approved** - Registration complete
- **Rejected** - Requires corrections

---

## Learning Programme

### 100-Day Curriculum

**Phase 1: Business Fundamentals (Days 1-25)**
- Business planning
- Market research
- Competitive analysis
- Value proposition

**Phase 2: Financial Management (Days 26-50)**
- Bookkeeping basics
- Financial statements
- Pricing strategy
- Cash flow management

**Phase 3: Operations & Marketing (Days 51-75)**
- Operational efficiency
- Digital marketing
- Customer service
- Brand building

**Phase 4: Growth & Compliance (Days 76-100)**
- Scaling strategies
- Legal requirements
- HR basics
- Regulatory compliance

### Lesson Format

Each lesson includes:
- Video (5-15 minutes)
- Transcript and captions
- Key takeaways
- Interactive quiz
- Downloadable resources

### Progress Tracking

- Completion percentage per module
- Quiz scores
- Time spent on lessons
- Certificates earned

---

## Dashboard

### Overview

Your dashboard shows:
- Registration status
- Learning progress
- Certificates earned
- Recommended next steps

### Quick Actions

- Continue to next lesson
- Review quiz results
- Download resources
- Share achievements
- Contact support

---

## Mobile App

### Download

- **iOS:** App Store (coming soon)
- **Android:** Google Play (coming soon)
- **Web:** Progressive Web App available

### Features

- Offline lesson access
- Push notifications
- Mobile-optimized video player
- Biometric login (optional)

### First Steps on Mobile

1. Download and install app
2. Sign in with your account
3. Enable push notifications
4. Download lessons for offline access

---

## Resources

### Downloadable Resources

- Business Plan Template (Word)
- Financial Tracking Spreadsheet (Excel)
- Marketing Calendar (Google Sheets)
- Customer Service Script (PDF)
- Social Media Content Calendar
- Business Registration Checklist
- Pricing Calculator Tool
- Break-Even Analysis Template

### Accessing Resources

1. Go to "Learning Centre"
2. Select a lesson
3. Scroll to "Resources" section
4. Click download button
5. File downloads to your device

---

## Certificates

### Earning Certificates

- Complete all 100 lessons
- Pass quizzes with 70%+ score
- Certificate issued automatically

### Viewing Certificates

1. Go to Dashboard
2. Click "Certificates" section
3. View earned certificates
4. Download or share

---

## Support

### Help Centre

Visit the FAQ section for common questions:
- How long is the programme?
- Can I download lessons?
- What if I miss a lesson?
- How do I get my certificate?

### Contact Support

- **Email:** support@remsana.com
- **Response Time:** Within 24 hours
- **Hours:** Monday-Friday, 9 AM - 5 PM WAT

### In-App Chat

- Live chat available during business hours
- Asynchronous messaging supported
- Quick response to queries

---

## Troubleshooting

### Login Issues

- Check email and password
- Reset password if needed
- Clear browser cache
- Try incognito mode

### Video Playback

- Check internet connection
- Try different browser
- Clear cache
- Contact support

### Mobile App Issues

- Update app to latest version
- Restart app
- Reinstall if needed
- Check device storage

---

## Tips for Success

1. **Set a Schedule**
   - Dedicate 15-20 minutes daily
   - Choose consistent time
   - Minimize distractions

2. **Take Notes**
   - Use downloadable templates
   - Review key takeaways
   - Apply learnings immediately

3. **Stay Engaged**
   - Complete quizzes
   - Download resources
   - Track your progress
   - Celebrate milestones

4. **Ask Questions**
   - Use in-app chat
   - Join community forum
   - Contact support
   - Connect with other users

---

**Document Version:** 1.0  
**Last Updated:** January 2026
EOF

echo -e "${YELLOW}[7/8]${NC} Creating documentation index..."

cat > "$DOCS_DIR/README.md" << 'EOF'
# Remsana Documentation

Welcome to the Remsana project documentation. This directory contains comprehensive documentation for developers, designers, and users.

---

## Documentation Structure

### 📋 [Project Overview](../PROJECT_OVERVIEW.md)
High-level overview of the Remsana platform, features, and technology stack.

### 🏗️ [Architecture Documentation](architecture/ARCHITECTURE.md)
System architecture, data flow, security, and scalability documentation.

### 🔌 [API Documentation](api/API_DOCUMENTATION.md)
Complete API reference with endpoints, request/response formats, and examples.

### 🚀 [Deployment Guide](deployment/DEPLOYMENT.md)
Step-by-step deployment instructions for development, staging, and production.

### 💻 [Development Guide](development/DEVELOPMENT_GUIDE.md)
Developer guide with setup instructions, coding standards, and best practices.

### 🎨 [Design System](design-system/DESIGN_SYSTEM.md)
Design tokens, components, and usage guidelines for the design system.

### 👥 [User Guide](user-guides/USER_GUIDE.md)
End-user documentation for using the Remsana platform.

---

## Quick Links

- **Figma Design:** https://www.figma.com/design/4cYe5d5idQXfUhJ3tF0YXv/REMSANA-Business-Builder
- **Setup Script:** `bash setup-remsana.sh`
- **Documentation Generator:** `bash generate-documentation.sh`

---

## Document Versions

All documentation is version 1.0, last updated January 2026.

---

## Contributing

When updating documentation:
1. Update the relevant document
2. Update version number
3. Update "Last Updated" date
4. Commit with message: `docs: Update [document name]`

---

**For questions or suggestions, please contact the development team.**
EOF

echo -e "${YELLOW}[8/8]${NC} Creating quick reference guide..."

cat > "$DOCS_DIR/QUICK_REFERENCE.md" << 'EOF'
# Remsana Quick Reference Guide

## Common Commands

### Development

```bash
# Install dependencies
npm install

# Start dev server
npm run dev

# Build for production
npm run build

# Run tests
npm test

# Lint code
npm run lint
```

### Docker

```bash
# Start all services
docker-compose up --build

# Stop services
docker-compose down

# View logs
docker-compose logs -f
```

### Project Setup

```bash
# Generate full project
bash setup-remsana.sh

# Generate documentation
bash generate-documentation.sh

# Install all dependencies
cd remsana && bash install.sh
```

---

## File Structure Quick Reference

```
REMSANA-Business-Builder-1/
├── src/                    # Design system
├── docs/                   # Documentation
├── setup-remsana.sh        # Project generator
├── generate-documentation.sh  # Doc generator
└── [Generated]
    ├── remsana-web/        # Web app
    └── remsana-mobile/     # Mobile app
```

---

## Environment Variables

### Web (.env.development)
```
VITE_API_URL=http://localhost:8000/api
VITE_APP_NAME=Remsana
VITE_APP_ENV=development
```

### Mobile (.env)
```
EXPO_PUBLIC_API_URL=http://localhost:8000/api
EXPO_PUBLIC_APP_NAME=Remsana
```

---

## API Endpoints Quick Reference

```
POST   /auth/login
POST   /auth/register
POST   /auth/refresh
GET    /businesses/registration-status
POST   /businesses/register
GET    /courses
GET    /lessons/:id
POST   /lessons/:id/complete
POST   /lessons/:id/quiz
```

---

## Design Tokens Quick Reference

### Colors
- Primary: `#1C1C8B`
- Accent: `#eda51f`
- Text: `#1F2121`
- Background: `#f3f0fa`

### Spacing
- 4px, 8px, 12px, 16px, 24px, 32px, 48px

### Typography
- H1: 32px
- H2: 24px
- H3: 18px
- Body: 14px

---

## Component Usage

```tsx
// Button
<Button variant="primary" size="lg">Click</Button>

// Card
<Card variant="hoverable">
  <CardContent>Content</CardContent>
</Card>

// Input
<Input type="email" placeholder="Email" />

// Modal
<Modal isOpen={open} onClose={() => setOpen(false)}>
  Content
</Modal>
```

---

## Useful Links

- [React Docs](https://react.dev/)
- [React Native Docs](https://reactnative.dev/)
- [Expo Docs](https://docs.expo.dev/)
- [Tailwind CSS](https://tailwindcss.com/)
- [Vite Docs](https://vitejs.dev/)

---

**Last Updated:** January 2026
EOF

# Final summary
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗"
echo "║        ✅ DOCUMENTATION GENERATION COMPLETE!                  ║"
echo "╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BLUE}📁 Documentation Structure Created:${NC}"
echo "  ✓ docs/PROJECT_OVERVIEW.md"
echo "  ✓ docs/architecture/ARCHITECTURE.md"
echo "  ✓ docs/api/API_DOCUMENTATION.md"
echo "  ✓ docs/deployment/DEPLOYMENT.md"
echo "  ✓ docs/development/DEVELOPMENT_GUIDE.md"
echo "  ✓ docs/design-system/DESIGN_SYSTEM.md"
echo "  ✓ docs/user-guides/USER_GUIDE.md"
echo "  ✓ docs/README.md"
echo "  ✓ docs/QUICK_REFERENCE.md"
echo ""

echo -e "${BLUE}📋 Documentation Files:${NC}"
echo "  • Main overview and index"
echo "  • Architecture and system design"
echo "  • Complete API reference"
echo "  • Deployment instructions"
echo "  • Development guide"
echo "  • Design system documentation"
echo "  • User guides"
echo "  • Quick reference"
echo ""

echo -e "${YELLOW}💡 Next Steps:${NC}"
echo "  1. Review generated documentation in docs/ directory"
echo "  2. Customize as needed for your project"
echo "  3. Update API endpoints if different"
echo "  4. Add project-specific details"
echo ""

echo -e "${GREEN}Documentation is ready! 🎉${NC}"
echo ""
