/**
 * Nigeria States and Local Government Areas (LGAs)
 * Complete data for all 36 states + FCT and their 774 LGAs
 */

export interface State {
  code: string;
  name: string;
}

export interface LGA {
  value: string;
  name: string;
}

export const NIGERIA_STATES: State[] = [
  { code: 'abia', name: 'Abia' },
  { code: 'adamawa', name: 'Adamawa' },
  { code: 'akwa-ibom', name: 'Akwa Ibom' },
  { code: 'anambra', name: 'Anambra' },
  { code: 'bauchi', name: 'Bauchi' },
  { code: 'bayelsa', name: 'Bayelsa' },
  { code: 'benue', name: 'Benue' },
  { code: 'borno', name: 'Borno' },
  { code: 'cross-river', name: 'Cross River' },
  { code: 'delta', name: 'Delta' },
  { code: 'ebonyi', name: 'Ebonyi' },
  { code: 'edo', name: 'Edo' },
  { code: 'ekiti', name: 'Ekiti' },
  { code: 'enugu', name: 'Enugu' },
  { code: 'fct', name: 'Federal Capital Territory' },
  { code: 'gombe', name: 'Gombe' },
  { code: 'imo', name: 'Imo' },
  { code: 'jigawa', name: 'Jigawa' },
  { code: 'kaduna', name: 'Kaduna' },
  { code: 'kano', name: 'Kano' },
  { code: 'katsina', name: 'Katsina' },
  { code: 'kebbi', name: 'Kebbi' },
  { code: 'kogi', name: 'Kogi' },
  { code: 'kwara', name: 'Kwara' },
  { code: 'lagos', name: 'Lagos' },
  { code: 'nasarawa', name: 'Nasarawa' },
  { code: 'niger', name: 'Niger' },
  { code: 'ogun', name: 'Ogun' },
  { code: 'ondo', name: 'Ondo' },
  { code: 'osun', name: 'Osun' },
  { code: 'oyo', name: 'Oyo' },
  { code: 'plateau', name: 'Plateau' },
  { code: 'rivers', name: 'Rivers' },
  { code: 'sokoto', name: 'Sokoto' },
  { code: 'taraba', name: 'Taraba' },
  { code: 'yobe', name: 'Yobe' },
  { code: 'zamfara', name: 'Zamfara' },
];

export const NIGERIA_LGA_BY_STATE: Record<string, LGA[]> = {
  'abia': [
    { value: 'aba-north', name: 'Aba North' },
    { value: 'aba-south', name: 'Aba South' },
    { value: 'arochukwu', name: 'Arochukwu' },
    { value: 'bende', name: 'Bende' },
    { value: 'ikwuano', name: 'Ikwuano' },
    { value: 'isiala-ngwa-north', name: 'Isiala Ngwa North' },
    { value: 'isiala-ngwa-south', name: 'Isiala Ngwa South' },
    { value: 'isuikwuato', name: 'Isuikwuato' },
    { value: 'obi-ngwa', name: 'Obi Ngwa' },
    { value: 'ohafia', name: 'Ohafia' },
    { value: 'osisioma-ngwa', name: 'Osisioma Ngwa' },
    { value: 'ugwunagbo', name: 'Ugwunagbo' },
    { value: 'ukwa-east', name: 'Ukwa East' },
    { value: 'ukwa-west', name: 'Ukwa West' },
    { value: 'umuahia-north', name: 'Umuahia North' },
    { value: 'umuahia-south', name: 'Umuahia South' },
    { value: 'umu-nneochi', name: 'Umu Nneochi' },
  ],
  'adamawa': [
    { value: 'demsa', name: 'Demsa' },
    { value: 'fufore', name: 'Fufore' },
    { value: 'ganye', name: 'Ganye' },
    { value: 'girei', name: 'Girei' },
    { value: 'gombi', name: 'Gombi' },
    { value: 'guyuk', name: 'Guyuk' },
    { value: 'hong', name: 'Hong' },
    { value: 'jada', name: 'Jada' },
    { value: 'lamurde', name: 'Lamurde' },
    { value: 'madagali', name: 'Madagali' },
    { value: 'maiha', name: 'Maiha' },
    { value: 'mayo-belwa', name: 'Mayo-Belwa' },
    { value: 'michika', name: 'Michika' },
    { value: 'mubi-north', name: 'Mubi North' },
    { value: 'mubi-south', name: 'Mubi South' },
    { value: 'numan', name: 'Numan' },
    { value: 'shelleng', name: 'Shelleng' },
    { value: 'song', name: 'Song' },
    { value: 'toungo', name: 'Toungo' },
    { value: 'yola-north', name: 'Yola North' },
    { value: 'yola-south', name: 'Yola South' },
  ],
  'akwa-ibom': [
    { value: 'abak', name: 'Abak' },
    { value: 'eastern-obolo', name: 'Eastern Obolo' },
    { value: 'eket', name: 'Eket' },
    { value: 'esit-eket', name: 'Esit Eket' },
    { value: 'essien-udim', name: 'Essien Udim' },
    { value: 'etim-ekpo', name: 'Etim Ekpo' },
    { value: 'etinan', name: 'Etinan' },
    { value: 'ibeno', name: 'Ibeno' },
    { value: 'ibesikpo-asutan', name: 'Ibesikpo Asutan' },
    { value: 'ibiono-ibom', name: 'Ibiono Ibom' },
    { value: 'ika', name: 'Ika' },
    { value: 'ikono', name: 'Ikono' },
    { value: 'ikot-abasi', name: 'Ikot Abasi' },
    { value: 'ikot-ekpene', name: 'Ikot Ekpene' },
    { value: 'ini', name: 'Ini' },
    { value: 'itu', name: 'Itu' },
    { value: 'mbo', name: 'Mbo' },
    { value: 'mkpat-enin', name: 'Mkpat Enin' },
    { value: 'nsit-atai', name: 'Nsit Atai' },
    { value: 'nsit-ibom', name: 'Nsit Ibom' },
    { value: 'nsit-ubium', name: 'Nsit Ubium' },
    { value: 'obot-akara', name: 'Obot Akara' },
    { value: 'okobo', name: 'Okobo' },
    { value: 'onna', name: 'Onna' },
    { value: 'oron', name: 'Oron' },
    { value: 'oruk-anam', name: 'Oruk Anam' },
    { value: 'udung-uko', name: 'Udung Uko' },
    { value: 'ukanafun', name: 'Ukanafun' },
    { value: 'uruan', name: 'Uruan' },
    { value: 'urue-offong-oruko', name: 'Urue-Offong/Oruko' },
    { value: 'uyo', name: 'Uyo' },
  ],
  'anambra': [
    { value: 'aguata', name: 'Aguata' },
    { value: 'anambra-east', name: 'Anambra East' },
    { value: 'anambra-west', name: 'Anambra West' },
    { value: 'anaocha', name: 'Anaocha' },
    { value: 'awka-north', name: 'Awka North' },
    { value: 'awka-south', name: 'Awka South' },
    { value: 'ayamelum', name: 'Ayamelum' },
    { value: 'dunukofia', name: 'Dunukofia' },
    { value: 'ekwusigo', name: 'Ekwusigo' },
    { value: 'idemili-north', name: 'Idemili North' },
    { value: 'idemili-south', name: 'Idemili South' },
    { value: 'ihiala', name: 'Ihiala' },
    { value: 'njikoka', name: 'Njikoka' },
    { value: 'nnewi-north', name: 'Nnewi North' },
    { value: 'nnewi-south', name: 'Nnewi South' },
    { value: 'ogbaru', name: 'Ogbaru' },
    { value: 'onitsha-north', name: 'Onitsha North' },
    { value: 'onitsha-south', name: 'Onitsha South' },
    { value: 'orumba-north', name: 'Orumba North' },
    { value: 'orumba-south', name: 'Orumba South' },
    { value: 'oyi', name: 'Oyi' },
  ],
  'bauchi': [
    { value: 'alkaleri', name: 'Alkaleri' },
    { value: 'bauchi', name: 'Bauchi' },
    { value: 'bogoro', name: 'Bogoro' },
    { value: 'damban', name: 'Damban' },
    { value: 'darazo', name: 'Darazo' },
    { value: 'dass', name: 'Dass' },
    { value: 'gamawa', name: 'Gamawa' },
    { value: 'ganjuwa', name: 'Ganjuwa' },
    { value: 'giade', name: 'Giade' },
    { value: 'itas-gadau', name: 'Itas/Gadau' },
    { value: 'jama-are', name: 'Jama\'are' },
    { value: 'katagum', name: 'Katagum' },
    { value: 'kirfi', name: 'Kirfi' },
    { value: 'misau', name: 'Misau' },
    { value: 'ningi', name: 'Ningi' },
    { value: 'shira', name: 'Shira' },
    { value: 'tafawa-balewa', name: 'Tafawa Balewa' },
    { value: 'toro', name: 'Toro' },
    { value: 'warji', name: 'Warji' },
    { value: 'zaki', name: 'Zaki' },
  ],
  'bayelsa': [
    { value: 'brass', name: 'Brass' },
    { value: 'ekeremor', name: 'Ekeremor' },
    { value: 'kolokuma-opokuma', name: 'Kolokuma/Opokuma' },
    { value: 'nembe', name: 'Nembe' },
    { value: 'ogbia', name: 'Ogbia' },
    { value: 'sagbama', name: 'Sagbama' },
    { value: 'southern-ijaw', name: 'Southern Ijaw' },
    { value: 'yenagoa', name: 'Yenagoa' },
  ],
  'benue': [
    { value: 'ado', name: 'Ado' },
    { value: 'agatu', name: 'Agatu' },
    { value: 'apa', name: 'Apa' },
    { value: 'buruku', name: 'Buruku' },
    { value: 'gboko', name: 'Gboko' },
    { value: 'guma', name: 'Guma' },
    { value: 'gwer-east', name: 'Gwer East' },
    { value: 'gwer-west', name: 'Gwer West' },
    { value: 'katsina-ala', name: 'Katsina-Ala' },
    { value: 'konshisha', name: 'Konshisha' },
    { value: 'kwande', name: 'Kwande' },
    { value: 'logo', name: 'Logo' },
    { value: 'makurdi', name: 'Makurdi' },
    { value: 'obi', name: 'Obi' },
    { value: 'ogbadibo', name: 'Ogbadibo' },
    { value: 'ohimini', name: 'Ohimini' },
    { value: 'oju', name: 'Oju' },
    { value: 'okpokwu', name: 'Okpokwu' },
    { value: 'otukpo', name: 'Otukpo' },
    { value: 'tarka', name: 'Tarka' },
    { value: 'ukum', name: 'Ukum' },
    { value: 'ushongo', name: 'Ushongo' },
    { value: 'vandeikya', name: 'Vandeikya' },
  ],
  'borno': [
    { value: 'abadam', name: 'Abadam' },
    { value: 'askira-uba', name: 'Askira/Uba' },
    { value: 'bama', name: 'Bama' },
    { value: 'bayo', name: 'Bayo' },
    { value: 'biu', name: 'Biu' },
    { value: 'chibok', name: 'Chibok' },
    { value: 'damboa', name: 'Damboa' },
    { value: 'dikwa', name: 'Dikwa' },
    { value: 'gubio', name: 'Gubio' },
    { value: 'guzamala', name: 'Guzamala' },
    { value: 'gwoza', name: 'Gwoza' },
    { value: 'hawul', name: 'Hawul' },
    { value: 'jere', name: 'Jere' },
    { value: 'kaga', name: 'Kaga' },
    { value: 'kala-balge', name: 'Kala/Balge' },
    { value: 'konduga', name: 'Konduga' },
    { value: 'kukawa', name: 'Kukawa' },
    { value: 'kwaya-kusar', name: 'Kwaya Kusar' },
    { value: 'mafa', name: 'Mafa' },
    { value: 'magumeri', name: 'Magumeri' },
    { value: 'maiduguri', name: 'Maiduguri' },
    { value: 'marte', name: 'Marte' },
    { value: 'mobbar', name: 'Mobbar' },
    { value: 'monguno', name: 'Monguno' },
    { value: 'ngala', name: 'Ngala' },
    { value: 'nganzai', name: 'Nganzai' },
    { value: 'shani', name: 'Shani' },
  ],
  'cross-river': [
    { value: 'abi', name: 'Abi' },
    { value: 'akamkpa', name: 'Akamkpa' },
    { value: 'akpabuyo', name: 'Akpabuyo' },
    { value: 'bakassi', name: 'Bakassi' },
    { value: 'bekwarra', name: 'Bekwarra' },
    { value: 'biase', name: 'Biase' },
    { value: 'boki', name: 'Boki' },
    { value: 'calabar-municipal', name: 'Calabar Municipal' },
    { value: 'calabar-south', name: 'Calabar South' },
    { value: 'etung', name: 'Etung' },
    { value: 'ikom', name: 'Ikom' },
    { value: 'obanliku', name: 'Obanliku' },
    { value: 'obubra', name: 'Obubra' },
    { value: 'obudu', name: 'Obudu' },
    { value: 'odukpani', name: 'Odukpani' },
    { value: 'ogoja', name: 'Ogoja' },
    { value: 'yakurr', name: 'Yakurr' },
    { value: 'yala', name: 'Yala' },
  ],
  'delta': [
    { value: 'aniocha-north', name: 'Aniocha North' },
    { value: 'aniocha-south', name: 'Aniocha South' },
    { value: 'bomadi', name: 'Bomadi' },
    { value: 'burutu', name: 'Burutu' },
    { value: 'ethiope-east', name: 'Ethiope East' },
    { value: 'ethiope-west', name: 'Ethiope West' },
    { value: 'ika-north-east', name: 'Ika North East' },
    { value: 'ika-south', name: 'Ika South' },
    { value: 'isoko-north', name: 'Isoko North' },
    { value: 'isoko-south', name: 'Isoko South' },
    { value: 'ndokwa-east', name: 'Ndokwa East' },
    { value: 'ndokwa-west', name: 'Ndokwa West' },
    { value: 'okpe', name: 'Okpe' },
    { value: 'oshimili-north', name: 'Oshimili North' },
    { value: 'oshimili-south', name: 'Oshimili South' },
    { value: 'patani', name: 'Patani' },
    { value: 'sapele', name: 'Sapele' },
    { value: 'udu', name: 'Udu' },
    { value: 'ughelli-north', name: 'Ughelli North' },
    { value: 'ughelli-south', name: 'Ughelli South' },
    { value: 'ukwuani', name: 'Ukwuani' },
    { value: 'uvwie', name: 'Uvwie' },
    { value: 'warri-north', name: 'Warri North' },
    { value: 'warri-south', name: 'Warri South' },
    { value: 'warri-south-west', name: 'Warri South West' },
  ],
  'ebonyi': [
    { value: 'abakaliki', name: 'Abakaliki' },
    { value: 'afikpo-north', name: 'Afikpo North' },
    { value: 'afikpo-south', name: 'Afikpo South' },
    { value: 'ebonyi', name: 'Ebonyi' },
    { value: 'ezza-north', name: 'Ezza North' },
    { value: 'ezza-south', name: 'Ezza South' },
    { value: 'ikwo', name: 'Ikwo' },
    { value: 'ishielu', name: 'Ishielu' },
    { value: 'ivo', name: 'Ivo' },
    { value: 'izzi', name: 'Izzi' },
    { value: 'ohaozara', name: 'Ohaozara' },
    { value: 'ohaukwu', name: 'Ohaukwu' },
    { value: 'onicha', name: 'Onicha' },
  ],
  'edo': [
    { value: 'akoko-edo', name: 'Akoko Edo' },
    { value: 'egor', name: 'Egor' },
    { value: 'esan-central', name: 'Esan Central' },
    { value: 'esan-north-east', name: 'Esan North-East' },
    { value: 'esan-south-east', name: 'Esan South-East' },
    { value: 'esan-west', name: 'Esan West' },
    { value: 'etsako-central', name: 'Etsako Central' },
    { value: 'etsako-east', name: 'Etsako East' },
    { value: 'etsako-west', name: 'Etsako West' },
    { value: 'igueben', name: 'Igueben' },
    { value: 'ikpoba-okha', name: 'Ikpoba-Okha' },
    { value: 'oredo', name: 'Oredo' },
    { value: 'orhionmwon', name: 'Orhionmwon' },
    { value: 'ovia-north-east', name: 'Ovia North-East' },
    { value: 'ovia-south-west', name: 'Ovia South-West' },
    { value: 'owan-east', name: 'Owan East' },
    { value: 'owan-west', name: 'Owan West' },
    { value: 'uhunmwonde', name: 'Uhunmwonde' },
  ],
  'ekiti': [
    { value: 'ado-ekiti', name: 'Ado Ekiti' },
    { value: 'efon', name: 'Efon' },
    { value: 'ekiti-east', name: 'Ekiti East' },
    { value: 'ekiti-south-west', name: 'Ekiti South-West' },
    { value: 'ekiti-west', name: 'Ekiti West' },
    { value: 'emure', name: 'Emure' },
    { value: 'gbonyin', name: 'Gbonyin' },
    { value: 'ido-osi', name: 'Ido-Osi' },
    { value: 'ijero', name: 'Ijero' },
    { value: 'ikere', name: 'Ikere' },
    { value: 'ikole', name: 'Ikole' },
    { value: 'ilejemeje', name: 'Ilejemeje' },
    { value: 'irepodun-ifelodun', name: 'Irepodun/Ifelodun' },
    { value: 'ise-orun', name: 'Ise/Orun' },
    { value: 'moba', name: 'Moba' },
    { value: 'oye', name: 'Oye' },
  ],
  'enugu': [
    { value: 'aninri', name: 'Aninri' },
    { value: 'awgu', name: 'Awgu' },
    { value: 'enugu-east', name: 'Enugu East' },
    { value: 'enugu-north', name: 'Enugu North' },
    { value: 'enugu-south', name: 'Enugu South' },
    { value: 'ezeagu', name: 'Ezeagu' },
    { value: 'igbo-etiti', name: 'Igbo Etiti' },
    { value: 'igbo-eze-north', name: 'Igbo Eze North' },
    { value: 'igbo-eze-south', name: 'Igbo Eze South' },
    { value: 'isi-uzo', name: 'Isi Uzo' },
    { value: 'nkanu-east', name: 'Nkanu East' },
    { value: 'nkanu-west', name: 'Nkanu West' },
    { value: 'nsukka', name: 'Nsukka' },
    { value: 'oji-river', name: 'Oji River' },
    { value: 'udenu', name: 'Udenu' },
    { value: 'udi', name: 'Udi' },
    { value: 'uzo-uwani', name: 'Uzo-Uwani' },
  ],
  'fct': [
    { value: 'abaji', name: 'Abaji' },
    { value: 'abuja-municipal', name: 'Abuja Municipal' },
    { value: 'bwari', name: 'Bwari' },
    { value: 'gwagwalada', name: 'Gwagwalada' },
    { value: 'kuje', name: 'Kuje' },
    { value: 'kwali', name: 'Kwali' },
  ],
  'gombe': [
    { value: 'akko', name: 'Akko' },
    { value: 'balanga', name: 'Balanga' },
    { value: 'billiri', name: 'Billiri' },
    { value: 'dukku', name: 'Dukku' },
    { value: 'funakaye', name: 'Funakaye' },
    { value: 'gombe', name: 'Gombe' },
    { value: 'kaltungo', name: 'Kaltungo' },
    { value: 'kwami', name: 'Kwami' },
    { value: 'nafada', name: 'Nafada' },
    { value: 'shongom', name: 'Shongom' },
    { value: 'yamaltu-deba', name: 'Yamaltu/Deba' },
  ],
  'imo': [
    { value: 'aboh-mbaise', name: 'Aboh Mbaise' },
    { value: 'ahiazu-mbaise', name: 'Ahiazu Mbaise' },
    { value: 'ehime-mbano', name: 'Ehime Mbano' },
    { value: 'ezinihitte', name: 'Ezinihitte' },
    { value: 'ideato-north', name: 'Ideato North' },
    { value: 'ideato-south', name: 'Ideato South' },
    { value: 'ihitte-uboma', name: 'Ihitte/Uboma' },
    { value: 'ikeduru', name: 'Ikeduru' },
    { value: 'isiala-mbano', name: 'Isiala Mbano' },
    { value: 'isu', name: 'Isu' },
    { value: 'mbaitoli', name: 'Mbaitoli' },
    { value: 'ngor-okpala', name: 'Ngor Okpala' },
    { value: 'njaba', name: 'Njaba' },
    { value: 'nkwerre', name: 'Nkwerre' },
    { value: 'nwangele', name: 'Nwangele' },
    { value: 'obowo', name: 'Obowo' },
    { value: 'oguta', name: 'Oguta' },
    { value: 'ohaji-egbema', name: 'Ohaji/Egbema' },
    { value: 'okigwe', name: 'Okigwe' },
    { value: 'onuimo', name: 'Onuimo' },
    { value: 'orlu', name: 'Orlu' },
    { value: 'orsu', name: 'Orsu' },
    { value: 'oru-east', name: 'Oru East' },
    { value: 'oru-west', name: 'Oru West' },
    { value: 'owerri-municipal', name: 'Owerri Municipal' },
    { value: 'owerri-north', name: 'Owerri North' },
    { value: 'owerri-west', name: 'Owerri West' },
  ],
  'jigawa': [
    { value: 'auyo', name: 'Auyo' },
    { value: 'babura', name: 'Babura' },
    { value: 'birniwa', name: 'Birniwa' },
    { value: 'birnin-kudu', name: 'Birnin Kudu' },
    { value: 'buji', name: 'Buji' },
    { value: 'dutse', name: 'Dutse' },
    { value: 'gagarawa', name: 'Gagarawa' },
    { value: 'garki', name: 'Garki' },
    { value: 'gumel', name: 'Gumel' },
    { value: 'guri', name: 'Guri' },
    { value: 'gwaram', name: 'Gwaram' },
    { value: 'gwiwa', name: 'Gwiwa' },
    { value: 'hadejia', name: 'Hadejia' },
    { value: 'jahun', name: 'Jahun' },
    { value: 'kafin-hausa', name: 'Kafin Hausa' },
    { value: 'kaugama', name: 'Kaugama' },
    { value: 'kazaure', name: 'Kazaure' },
    { value: 'kiri-kasama', name: 'Kiri Kasama' },
    { value: 'kiyawa', name: 'Kiyawa' },
    { value: 'maigatari', name: 'Maigatari' },
    { value: 'malam-madori', name: 'Malam Madori' },
    { value: 'miga', name: 'Miga' },
    { value: 'ringim', name: 'Ringim' },
    { value: 'roni', name: 'Roni' },
    { value: 'sule-tankarkar', name: 'Sule Tankarkar' },
    { value: 'taura', name: 'Taura' },
    { value: 'yankwashi', name: 'Yankwashi' },
  ],
  'kaduna': [
    { value: 'birnin-gwari', name: 'Birnin Gwari' },
    { value: 'chikun', name: 'Chikun' },
    { value: 'giwa', name: 'Giwa' },
    { value: 'igabi', name: 'Igabi' },
    { value: 'ikara', name: 'Ikara' },
    { value: 'jaba', name: 'Jaba' },
    { value: 'jema-a', name: 'Jema\'a' },
    { value: 'kachia', name: 'Kachia' },
    { value: 'kaduna-north', name: 'Kaduna North' },
    { value: 'kaduna-south', name: 'Kaduna South' },
    { value: 'kagarko', name: 'Kagarko' },
    { value: 'kajuru', name: 'Kajuru' },
    { value: 'kaura', name: 'Kaura' },
    { value: 'kauru', name: 'Kauru' },
    { value: 'kubau', name: 'Kubau' },
    { value: 'kudan', name: 'Kudan' },
    { value: 'lere', name: 'Lere' },
    { value: 'makarfi', name: 'Makarfi' },
    { value: 'sabon-gari', name: 'Sabon Gari' },
    { value: 'sanga', name: 'Sanga' },
    { value: 'soba', name: 'Soba' },
    { value: 'zangon-kataf', name: 'Zangon Kataf' },
    { value: 'zaria', name: 'Zaria' },
  ],
  'kano': [
    { value: 'ajingi', name: 'Ajingi' },
    { value: 'albasu', name: 'Albasu' },
    { value: 'bagwai', name: 'Bagwai' },
    { value: 'bebeji', name: 'Bebeji' },
    { value: 'bichi', name: 'Bichi' },
    { value: 'bunkure', name: 'Bunkure' },
    { value: 'dala', name: 'Dala' },
    { value: 'dambatta', name: 'Dambatta' },
    { value: 'dawakin-kudu', name: 'Dawakin Kudu' },
    { value: 'dawakin-tofa', name: 'Dawakin Tofa' },
    { value: 'doguwa', name: 'Doguwa' },
    { value: 'fagge', name: 'Fagge' },
    { value: 'gabasawa', name: 'Gabasawa' },
    { value: 'garko', name: 'Garko' },
    { value: 'garun-mallam', name: 'Garun Mallam' },
    { value: 'gaya', name: 'Gaya' },
    { value: 'gezawa', name: 'Gezawa' },
    { value: 'gwale', name: 'Gwale' },
    { value: 'gwarzo', name: 'Gwarzo' },
    { value: 'kabo', name: 'Kabo' },
    { value: 'kano-municipal', name: 'Kano Municipal' },
    { value: 'karaye', name: 'Karaye' },
    { value: 'kibiya', name: 'Kibiya' },
    { value: 'kiru', name: 'Kiru' },
    { value: 'kumbotso', name: 'Kumbotso' },
    { value: 'kunchi', name: 'Kunchi' },
    { value: 'kura', name: 'Kura' },
    { value: 'madobi', name: 'Madobi' },
    { value: 'makoda', name: 'Makoda' },
    { value: 'minjibir', name: 'Minjibir' },
    { value: 'nasarawa', name: 'Nasarawa' },
    { value: 'rano', name: 'Rano' },
    { value: 'rimin-gado', name: 'Rimin Gado' },
    { value: 'rogo', name: 'Rogo' },
    { value: 'shanono', name: 'Shanono' },
    { value: 'sumaila', name: 'Sumaila' },
    { value: 'takai', name: 'Takai' },
    { value: 'tarauni', name: 'Tarauni' },
    { value: 'tofa', name: 'Tofa' },
    { value: 'tsanyawa', name: 'Tsanyawa' },
    { value: 'tudun-wada', name: 'Tudun Wada' },
    { value: 'ungogo', name: 'Ungogo' },
    { value: 'warawa', name: 'Warawa' },
    { value: 'wudil', name: 'Wudil' },
  ],
  'katsina': [
    { value: 'bakori', name: 'Bakori' },
    { value: 'batagarawa', name: 'Batagarawa' },
    { value: 'batsari', name: 'Batsari' },
    { value: 'baure', name: 'Baure' },
    { value: 'bindawa', name: 'Bindawa' },
    { value: 'charanchi', name: 'Charanchi' },
    { value: 'dan-musa', name: 'Dan Musa' },
    { value: 'dandume', name: 'Dandume' },
    { value: 'danja', name: 'Danja' },
    { value: 'daura', name: 'Daura' },
    { value: 'dutsi', name: 'Dutsi' },
    { value: 'dutsin-ma', name: 'Dutsin-Ma' },
    { value: 'faskari', name: 'Faskari' },
    { value: 'funtua', name: 'Funtua' },
    { value: 'ingawa', name: 'Ingawa' },
    { value: 'jibia', name: 'Jibia' },
    { value: 'kafur', name: 'Kafur' },
    { value: 'kaita', name: 'Kaita' },
    { value: 'kankara', name: 'Kankara' },
    { value: 'kankia', name: 'Kankia' },
    { value: 'katsina', name: 'Katsina' },
    { value: 'kurfi', name: 'Kurfi' },
    { value: 'kusada', name: 'Kusada' },
    { value: 'mai-adua', name: 'Mai\'Adua' },
    { value: 'malumfashi', name: 'Malumfashi' },
    { value: 'mani', name: 'Mani' },
    { value: 'mashi', name: 'Mashi' },
    { value: 'matazu', name: 'Matazu' },
    { value: 'musawa', name: 'Musawa' },
    { value: 'rimi', name: 'Rimi' },
    { value: 'sabuwa', name: 'Sabuwa' },
    { value: 'safana', name: 'Safana' },
    { value: 'sandamu', name: 'Sandamu' },
    { value: 'zango', name: 'Zango' },
  ],
  'kebbi': [
    { value: 'aleiro', name: 'Aleiro' },
    { value: 'arewa-dandi', name: 'Arewa Dandi' },
    { value: 'argungu', name: 'Argungu' },
    { value: 'augie', name: 'Augie' },
    { value: 'bagudo', name: 'Bagudo' },
    { value: 'birnin-kebbi', name: 'Birnin Kebbi' },
    { value: 'bunza', name: 'Bunza' },
    { value: 'dandi', name: 'Dandi' },
    { value: 'fakai', name: 'Fakai' },
    { value: 'gwandu', name: 'Gwandu' },
    { value: 'jega', name: 'Jega' },
    { value: 'kalgo', name: 'Kalgo' },
    { value: 'koko-besse', name: 'Koko/Besse' },
    { value: 'maiyama', name: 'Maiyama' },
    { value: 'ngaski', name: 'Ngaski' },
    { value: 'sakaba', name: 'Sakaba' },
    { value: 'shanga', name: 'Shanga' },
    { value: 'suru', name: 'Suru' },
    { value: 'wasagu-danko', name: 'Wasagu/Danko' },
    { value: 'yauri', name: 'Yauri' },
    { value: 'zuru', name: 'Zuru' },
  ],
  'kogi': [
    { value: 'adavi', name: 'Adavi' },
    { value: 'ajaokuta', name: 'Ajaokuta' },
    { value: 'ankpa', name: 'Ankpa' },
    { value: 'bassa', name: 'Bassa' },
    { value: 'dekina', name: 'Dekina' },
    { value: 'ibaji', name: 'Ibaji' },
    { value: 'idah', name: 'Idah' },
    { value: 'igalamela-odolu', name: 'Igalamela-Odolu' },
    { value: 'ijumu', name: 'Ijumu' },
    { value: 'kabba-bunu', name: 'Kabba/Bunu' },
    { value: 'kogi', name: 'Kogi' },
    { value: 'lokoja', name: 'Lokoja' },
    { value: 'mopa-muro', name: 'Mopa-Muro' },
    { value: 'ofu', name: 'Ofu' },
    { value: 'ogori-magongo', name: 'Ogori/Magongo' },
    { value: 'okehi', name: 'Okehi' },
    { value: 'okene', name: 'Okene' },
    { value: 'olamaboro', name: 'Olamaboro' },
    { value: 'omala', name: 'Omala' },
    { value: 'yagba-east', name: 'Yagba East' },
    { value: 'yagba-west', name: 'Yagba West' },
  ],
  'kwara': [
    { value: 'asa', name: 'Asa' },
    { value: 'baruten', name: 'Baruten' },
    { value: 'edu', name: 'Edu' },
    { value: 'ekiti', name: 'Ekiti' },
    { value: 'ifelodun', name: 'Ifelodun' },
    { value: 'ilorin-east', name: 'Ilorin East' },
    { value: 'ilorin-south', name: 'Ilorin South' },
    { value: 'ilorin-west', name: 'Ilorin West' },
    { value: 'irepodun', name: 'Irepodun' },
    { value: 'isin', name: 'Isin' },
    { value: 'kaiama', name: 'Kaiama' },
    { value: 'moro', name: 'Moro' },
    { value: 'offa', name: 'Offa' },
    { value: 'oke-ero', name: 'Oke Ero' },
    { value: 'oyun', name: 'Oyun' },
    { value: 'pategi', name: 'Pategi' },
  ],
  'lagos': [
    { value: 'agege', name: 'Agege' },
    { value: 'ajeromi-ifelodun', name: 'Ajeromi-Ifelodun' },
    { value: 'alimosho', name: 'Alimosho' },
    { value: 'amuwo-odofin', name: 'Amuwo-Odofin' },
    { value: 'apapa', name: 'Apapa' },
    { value: 'badagry', name: 'Badagry' },
    { value: 'epe', name: 'Epe' },
    { value: 'eti-osa', name: 'Eti-Osa' },
    { value: 'ibeju-lekki', name: 'Ibeju-Lekki' },
    { value: 'ifako-ijaiye', name: 'Ifako-Ijaiye' },
    { value: 'ikeja', name: 'Ikeja' },
    { value: 'ikorodu', name: 'Ikorodu' },
    { value: 'kosofe', name: 'Kosofe' },
    { value: 'lagos-island', name: 'Lagos Island' },
    { value: 'lagos-mainland', name: 'Lagos Mainland' },
    { value: 'mushin', name: 'Mushin' },
    { value: 'ojo', name: 'Ojo' },
    { value: 'oshodi-isolo', name: 'Oshodi-Isolo' },
    { value: 'shomolu', name: 'Shomolu' },
    { value: 'surulere', name: 'Surulere' },
  ],
  'nasarawa': [
    { value: 'akwanga', name: 'Akwanga' },
    { value: 'awe', name: 'Awe' },
    { value: 'doma', name: 'Doma' },
    { value: 'karu', name: 'Karu' },
    { value: 'keana', name: 'Keana' },
    { value: 'keffi', name: 'Keffi' },
    { value: 'kokona', name: 'Kokona' },
    { value: 'lafia', name: 'Lafia' },
    { value: 'nasarawa', name: 'Nasarawa' },
    { value: 'nasarawa-egon', name: 'Nasarawa Egon' },
    { value: 'obi', name: 'Obi' },
    { value: 'toto', name: 'Toto' },
    { value: 'wamba', name: 'Wamba' },
  ],
  'niger': [
    { value: 'agaie', name: 'Agaie' },
    { value: 'agwara', name: 'Agwara' },
    { value: 'bida', name: 'Bida' },
    { value: 'borgu', name: 'Borgu' },
    { value: 'bosso', name: 'Bosso' },
    { value: 'chanchaga', name: 'Chanchaga' },
    { value: 'edati', name: 'Edati' },
    { value: 'gbako', name: 'Gbako' },
    { value: 'gurara', name: 'Gurara' },
    { value: 'katcha', name: 'Katcha' },
    { value: 'kontagora', name: 'Kontagora' },
    { value: 'lapai', name: 'Lapai' },
    { value: 'lavun', name: 'Lavun' },
    { value: 'magama', name: 'Magama' },
    { value: 'mariga', name: 'Mariga' },
    { value: 'mashegu', name: 'Mashegu' },
    { value: 'mokwa', name: 'Mokwa' },
    { value: 'moya', name: 'Moya' },
    { value: 'paikoro', name: 'Paikoro' },
    { value: 'rafi', name: 'Rafi' },
    { value: 'rijau', name: 'Rijau' },
    { value: 'shiroro', name: 'Shiroro' },
    { value: 'suleja', name: 'Suleja' },
    { value: 'tafa', name: 'Tafa' },
    { value: 'wushishi', name: 'Wushishi' },
  ],
  'ogun': [
    { value: 'abeokuta-north', name: 'Abeokuta North' },
    { value: 'abeokuta-south', name: 'Abeokuta South' },
    { value: 'ado-odo-ota', name: 'Ado-Odo/Ota' },
    { value: 'egbado-north', name: 'Egbado North' },
    { value: 'egbado-south', name: 'Egbado South' },
    { value: 'ewekoro', name: 'Ewekoro' },
    { value: 'ifo', name: 'Ifo' },
    { value: 'ijebu-east', name: 'Ijebu East' },
    { value: 'ijebu-north', name: 'Ijebu North' },
    { value: 'ijebu-north-east', name: 'Ijebu North East' },
    { value: 'ijebu-ode', name: 'Ijebu Ode' },
    { value: 'ikenne', name: 'Ikenne' },
    { value: 'imeko-afon', name: 'Imeko Afon' },
    { value: 'ipokia', name: 'Ipokia' },
    { value: 'obafemi-owode', name: 'Obafemi Owode' },
    { value: 'odeda', name: 'Odeda' },
    { value: 'odogbolu', name: 'Odogbolu' },
    { value: 'ogun-waterside', name: 'Ogun Waterside' },
    { value: 'remo-north', name: 'Remo North' },
    { value: 'shagamu', name: 'Shagamu' },
  ],
  'ondo': [
    { value: 'akoko-north-east', name: 'Akoko North-East' },
    { value: 'akoko-north-west', name: 'Akoko North-West' },
    { value: 'akoko-south-east', name: 'Akoko South-East' },
    { value: 'akoko-south-west', name: 'Akoko South-West' },
    { value: 'akure-north', name: 'Akure North' },
    { value: 'akure-south', name: 'Akure South' },
    { value: 'ese-odo', name: 'Ese Odo' },
    { value: 'idanre', name: 'Idanre' },
    { value: 'ifedore', name: 'Ifedore' },
    { value: 'ilaje', name: 'Ilaje' },
    { value: 'ile-oluji-okeigbo', name: 'Ile Oluji/Okeigbo' },
    { value: 'irele', name: 'Irele' },
    { value: 'odigbo', name: 'Odigbo' },
    { value: 'okitipupa', name: 'Okitipupa' },
    { value: 'ondo-east', name: 'Ondo East' },
    { value: 'ondo-west', name: 'Ondo West' },
    { value: 'ose', name: 'Ose' },
    { value: 'owo', name: 'Owo' },
  ],
  'osun': [
    { value: 'aiyedaade', name: 'Aiyedaade' },
    { value: 'aiyedire', name: 'Aiyedire' },
    { value: 'atakumosa-east', name: 'Atakumosa East' },
    { value: 'atakumosa-west', name: 'Atakumosa West' },
    { value: 'boluwaduro', name: 'Boluwaduro' },
    { value: 'boripe', name: 'Boripe' },
    { value: 'ede-north', name: 'Ede North' },
    { value: 'ede-south', name: 'Ede South' },
    { value: 'egbedore', name: 'Egbedore' },
    { value: 'ejigbo', name: 'Ejigbo' },
    { value: 'ife-central', name: 'Ife Central' },
    { value: 'ife-east', name: 'Ife East' },
    { value: 'ife-north', name: 'Ife North' },
    { value: 'ife-south', name: 'Ife South' },
    { value: 'ifedayo', name: 'Ifedayo' },
    { value: 'ifelodun', name: 'Ifelodun' },
    { value: 'ila', name: 'Ila' },
    { value: 'ilesa-east', name: 'Ilesa East' },
    { value: 'ilesa-west', name: 'Ilesa West' },
    { value: 'irepodun', name: 'Irepodun' },
    { value: 'irewole', name: 'Irewole' },
    { value: 'isokan', name: 'Isokan' },
    { value: 'iwo', name: 'Iwo' },
    { value: 'obokun', name: 'Obokun' },
    { value: 'odo-otin', name: 'Odo Otin' },
    { value: 'ola-oluwa', name: 'Ola Oluwa' },
    { value: 'olorunda', name: 'Olorunda' },
    { value: 'oriade', name: 'Oriade' },
    { value: 'orolu', name: 'Orolu' },
    { value: 'osogbo', name: 'Osogbo' },
  ],
  'oyo': [
    { value: 'afijio', name: 'Afijio' },
    { value: 'akinyele', name: 'Akinyele' },
    { value: 'atiba', name: 'Atiba' },
    { value: 'atisbo', name: 'Atisbo' },
    { value: 'egbeda', name: 'Egbeda' },
    { value: 'ibadan-north', name: 'Ibadan North' },
    { value: 'ibadan-north-east', name: 'Ibadan North-East' },
    { value: 'ibadan-north-west', name: 'Ibadan North-West' },
    { value: 'ibadan-south-east', name: 'Ibadan South-East' },
    { value: 'ibadan-south-west', name: 'Ibadan South-West' },
    { value: 'ibarapa-central', name: 'Ibarapa Central' },
    { value: 'ibarapa-east', name: 'Ibarapa East' },
    { value: 'ibarapa-north', name: 'Ibarapa North' },
    { value: 'ido', name: 'Ido' },
    { value: 'irepo', name: 'Irepo' },
    { value: 'iseyin', name: 'Iseyin' },
    { value: 'itesiwaju', name: 'Itesiwaju' },
    { value: 'iwajowa', name: 'Iwajowa' },
    { value: 'kajola', name: 'Kajola' },
    { value: 'lagelu', name: 'Lagelu' },
    { value: 'ogbomosho-north', name: 'Ogbomosho North' },
    { value: 'ogbomosho-south', name: 'Ogbomosho South' },
    { value: 'ogo-oluwa', name: 'Ogo Oluwa' },
    { value: 'olorunsogo', name: 'Olorunsogo' },
    { value: 'oluyole', name: 'Oluyole' },
    { value: 'ona-ara', name: 'Ona Ara' },
    { value: 'orelope', name: 'Orelope' },
    { value: 'ori-ire', name: 'Ori Ire' },
    { value: 'oyo-east', name: 'Oyo East' },
    { value: 'oyo-west', name: 'Oyo West' },
    { value: 'saki-east', name: 'Saki East' },
    { value: 'saki-west', name: 'Saki West' },
    { value: 'surulere', name: 'Surulere' },
  ],
  'plateau': [
    { value: 'barkin-ladi', name: 'Barkin Ladi' },
    { value: 'bassa', name: 'Bassa' },
    { value: 'bokkos', name: 'Bokkos' },
    { value: 'jos-east', name: 'Jos East' },
    { value: 'jos-north', name: 'Jos North' },
    { value: 'jos-south', name: 'Jos South' },
    { value: 'kanam', name: 'Kanam' },
    { value: 'kanke', name: 'Kanke' },
    { value: 'langtang-north', name: 'Langtang North' },
    { value: 'langtang-south', name: 'Langtang South' },
    { value: 'mangu', name: 'Mangu' },
    { value: 'mikang', name: 'Mikang' },
    { value: 'pankshin', name: 'Pankshin' },
    { value: 'qua-an-pan', name: 'Qua\'an Pan' },
    { value: 'riyom', name: 'Riyom' },
    { value: 'shendam', name: 'Shendam' },
    { value: 'wase', name: 'Wase' },
  ],
  'rivers': [
    { value: 'abua-odual', name: 'Abua/Odual' },
    { value: 'ahoada-east', name: 'Ahoada East' },
    { value: 'ahoada-west', name: 'Ahoada West' },
    { value: 'akuku-toru', name: 'Akuku-Toru' },
    { value: 'andoni', name: 'Andoni' },
    { value: 'asari-toru', name: 'Asari-Toru' },
    { value: 'bonny', name: 'Bonny' },
    { value: 'degema', name: 'Degema' },
    { value: 'eleme', name: 'Eleme' },
    { value: 'emuoha', name: 'Emuoha' },
    { value: 'etche', name: 'Etche' },
    { value: 'gokana', name: 'Gokana' },
    { value: 'ikwerre', name: 'Ikwerre' },
    { value: 'khana', name: 'Khana' },
    { value: 'obio-akpor', name: 'Obio/Akpor' },
    { value: 'ogba-egbema-ndoni', name: 'Ogba/Egbema/Ndoni' },
    { value: 'ogu-bolo', name: 'Ogu/Bolo' },
    { value: 'okrika', name: 'Okrika' },
    { value: 'omuma', name: 'Omuma' },
    { value: 'opobo-nkoro', name: 'Opobo/Nkoro' },
    { value: 'oyigbo', name: 'Oyigbo' },
    { value: 'port-harcourt', name: 'Port Harcourt' },
    { value: 'tai', name: 'Tai' },
  ],
  'sokoto': [
    { value: 'binji', name: 'Binji' },
    { value: 'bodinga', name: 'Bodinga' },
    { value: 'dange-shuni', name: 'Dange Shuni' },
    { value: 'gada', name: 'Gada' },
    { value: 'goronyo', name: 'Goronyo' },
    { value: 'gudu', name: 'Gudu' },
    { value: 'gwadabawa', name: 'Gwadabawa' },
    { value: 'illela', name: 'Illela' },
    { value: 'isa', name: 'Isa' },
    { value: 'kebbe', name: 'Kebbe' },
    { value: 'kware', name: 'Kware' },
    { value: 'rabah', name: 'Rabah' },
    { value: 'sabon-birni', name: 'Sabon Birni' },
    { value: 'shagari', name: 'Shagari' },
    { value: 'silame', name: 'Silame' },
    { value: 'sokoto-north', name: 'Sokoto North' },
    { value: 'sokoto-south', name: 'Sokoto South' },
    { value: 'tambuwal', name: 'Tambuwal' },
    { value: 'tangaza', name: 'Tangaza' },
    { value: 'tureta', name: 'Tureta' },
    { value: 'wamako', name: 'Wamako' },
    { value: 'wurno', name: 'Wurno' },
    { value: 'yabo', name: 'Yabo' },
  ],
  'taraba': [
    { value: 'ardo-kola', name: 'Ardo Kola' },
    { value: 'bali', name: 'Bali' },
    { value: 'donga', name: 'Donga' },
    { value: 'gashaka', name: 'Gashaka' },
    { value: 'gassol', name: 'Gassol' },
    { value: 'ibi', name: 'Ibi' },
    { value: 'jalingo', name: 'Jalingo' },
    { value: 'karim-lamido', name: 'Karim Lamido' },
    { value: 'kumi', name: 'Kumi' },
    { value: 'lau', name: 'Lau' },
    { value: 'sardauna', name: 'Sardauna' },
    { value: 'takum', name: 'Takum' },
    { value: 'ussa', name: 'Ussa' },
    { value: 'wukari', name: 'Wukari' },
    { value: 'yorro', name: 'Yorro' },
    { value: 'zing', name: 'Zing' },
  ],
  'yobe': [
    { value: 'bade', name: 'Bade' },
    { value: 'bursari', name: 'Bursari' },
    { value: 'damaturu', name: 'Damaturu' },
    { value: 'fika', name: 'Fika' },
    { value: 'fune', name: 'Fune' },
    { value: 'geidam', name: 'Geidam' },
    { value: 'gujba', name: 'Gujba' },
    { value: 'gulani', name: 'Gulani' },
    { value: 'jakusko', name: 'Jakusko' },
    { value: 'karasuwa', name: 'Karasuwa' },
    { value: 'machina', name: 'Machina' },
    { value: 'nangere', name: 'Nangere' },
    { value: 'nguru', name: 'Nguru' },
    { value: 'potiskum', name: 'Potiskum' },
    { value: 'tarmuwa', name: 'Tarmuwa' },
    { value: 'yunusari', name: 'Yunusari' },
    { value: 'yusufari', name: 'Yusufari' },
  ],
  'zamfara': [
    { value: 'anka', name: 'Anka' },
    { value: 'bakura', name: 'Bakura' },
    { value: 'birnin-magaji-kiyaw', name: 'Birnin Magaji/Kiyaw' },
    { value: 'bukkuyum', name: 'Bukkuyum' },
    { value: 'bungudu', name: 'Bungudu' },
    { value: 'gummi', name: 'Gummi' },
    { value: 'gusau', name: 'Gusau' },
    { value: 'kaura-namoda', name: 'Kaura Namoda' },
    { value: 'maradun', name: 'Maradun' },
    { value: 'maru', name: 'Maru' },
    { value: 'shinkafi', name: 'Shinkafi' },
    { value: 'talata-mafara', name: 'Talata Mafara' },
    { value: 'tsafe', name: 'Tsafe' },
    { value: 'zurmi', name: 'Zurmi' },
  ],
};

/**
 * Get LGAs for a specific state
 * @param stateCode - The state code (e.g., 'lagos', 'fct')
 * @returns Array of LGAs for the state, or empty array if not found
 */
export function getLGAsByState(stateCode: string): LGA[] {
  return NIGERIA_LGA_BY_STATE[stateCode] || [];
}

/**
 * Get state name from state code
 * @param stateCode - The state code
 * @returns State name or empty string if not found
 */
export function getStateName(stateCode: string): string {
  const state = NIGERIA_STATES.find(s => s.code === stateCode);
  return state?.name || '';
}
